version: '3.8'

services:
  web:
    build: .
    command: gunicorn gotopa_project.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8002:8000"
    volumes:
      # Төслийн кодоо холбох
      - .:/app
      # SQLite файл байрлах хавтасыг тусгаарлаж Named Volume-д хадгалах
      - sqlite_data:/app/sqlite_db
    environment:
      - DEBUG=1

volumes:
  sqlite_data:  # Windows дээрх SQLite-ийн түгжээний алдаанаас сэргийлнэ