version: '3.8'

services:
  web:
    build: .
    command: sh -c "python manage.py collectstatic --noinput && gunicorn gotopa_project.wsgi:application --bind 0.0.0.0:8000 --workers 2 --timeout 90 --max-requests 300 --max-requests-jitter 30"
    ports:
      - "8002:8000"
    volumes:
      # Төслийн кодоо холбох
      - .:/app
      # SQLite файл байрлах хавтасыг тусгаарлаж Named Volume-д хадгалах
      - sqlite_data:/app/sqlite_db
    environment:
      - DJANGO_DEBUG=False

volumes:
  sqlite_data:  # Windows дээрх SQLite-ийн түгжээний алдаанаас сэргийлнэ