# Generated by Django 6.0 on 2026-01-03 23:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Нэр')),
                ('level', models.CharField(choices=[('BEGINNER', 'Анхан шат'), ('INTERMEDIATE', 'Дунд шат'), ('ADVANCED', 'Дээд шат'), ('VIP', 'VIP')], max_length=20, verbose_name='Түвшин')),
                ('description', models.TextField(blank=True, verbose_name='Тайлбар')),
                ('duration_weeks', models.IntegerField(verbose_name='Үргэлжлэх хугацаа (долоо хоног)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Үнэ (₮)')),
                ('start_date', models.DateField(verbose_name='Эхлэх өдөр')),
                ('end_date', models.DateField(verbose_name='Дуусах өдөр')),
                ('max_students', models.IntegerField(default=30, verbose_name='Дээд хязгаар')),
                ('is_active', models.BooleanField(default=True, verbose_name='Идэвхтэй')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Сургалт',
                'verbose_name_plural': 'Сургалтууд',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('PRESIDENT', 'Тэргүүн'), ('DIRECTOR', 'Захирал'), ('MANAGER', 'Менежер'), ('TEACHER_BEGINNER', 'Анхан шатны багш'), ('TEACHER_INTERMEDIATE', 'Дунд шатны багш'), ('TEACHER_ADVANCED', 'Дээд шатны багш'), ('STUDENT', 'Сурагч')], default='STUDENT', max_length=30, verbose_name='Эрх')),
                ('mongolian_name', models.CharField(blank=True, max_length=200, verbose_name='Монгол нэр')),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Утасны дугаар +976XXXXXXXX форматтай байх ёстой', regex='^\\+?976?\\d{8,}$')], verbose_name='Утас')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Төрсөн өдөр')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Эрэгтэй'), ('F', 'Эмэгтэй')], max_length=10, verbose_name='Хүйс')),
                ('address', models.TextField(blank=True, verbose_name='Хаяг')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Хот/Аймаг')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='Дүүрэг/Сум')),
                ('enrollment_date', models.DateField(blank=True, null=True, verbose_name='Элссэн огноо')),
                ('is_active_student', models.BooleanField(default=True, verbose_name='Идэвхтэй эсэх')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='Зураг')),
                ('notes', models.TextField(blank=True, verbose_name='Тэмдэглэл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Үүсгэсэн огноо')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Шинэчилсэн огноо')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Хэрэглэгчийн мэдээлэл',
                'verbose_name_plural': 'Хэрэглэгчдийн мэдээлэл',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_date', models.DateField(auto_now_add=True, verbose_name='Бүртгүүлсэн өдөр')),
                ('status', models.CharField(choices=[('PENDING', 'Хүлээгдэж буй'), ('APPROVED', 'Баталсан'), ('COMPLETED', 'Төгссөн'), ('CANCELLED', 'Цуцалсан')], default='PENDING', max_length=20, verbose_name='Төлөв')),
                ('payment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Төлсөн дүн (₮)')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Төлсөн өдөр')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Төлбөр төлсөн')),
                ('certificate_issued', models.BooleanField(default=False, verbose_name='Гэрчилгээ олгосон')),
                ('certificate_date', models.DateField(blank=True, null=True, verbose_name='Гэрчилгээ олгосон өдөр')),
                ('is_active', models.BooleanField(default=True, verbose_name='Идэвхтэй')),
                ('notes', models.TextField(blank=True, verbose_name='Тэмдэглэл')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='main.course', verbose_name='Сургалт')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='main.userprofile', verbose_name='Сурагч')),
            ],
            options={
                'verbose_name': 'Бүртгэл',
                'verbose_name_plural': 'Бүртгэлүүд',
                'ordering': ['-enrolled_date'],
                'unique_together': {('student', 'course')},
            },
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['TEACHER_BEGINNER', 'TEACHER_INTERMEDIATE', 'TEACHER_ADVANCED']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_teaching', to='main.userprofile', verbose_name='Багш'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Огноо')),
                ('present', models.BooleanField(default=True, verbose_name='Ирсэн')),
                ('notes', models.TextField(blank=True, verbose_name='Тэмдэглэл')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='main.enrollment', verbose_name='Бүртгэл')),
            ],
            options={
                'verbose_name': 'Ирц',
                'verbose_name_plural': 'Ирцүүд',
                'ordering': ['-date'],
                'unique_together': {('enrollment', 'date')},
            },
        ),
    ]
