# Generated by Django 6.0 on 2026-01-17 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Агуулгыг ялгах түлхүүр (жишээ: home_hero_title)', max_length=100, unique=True, verbose_name='Түлхүүр')),
                ('title', models.CharField(help_text='Админ панел дээр харагдах нэр', max_length=200, verbose_name='Гарчиг')),
                ('content', models.TextField(help_text='Вэб дээр харагдах текст', verbose_name='Агуулга')),
                ('page', models.CharField(choices=[('home', 'Нүүр хуудас'), ('about', 'Бидний тухай'), ('courses', 'Хичээлүүд'), ('contact', 'Холбоо барих'), ('other', 'Бусад')], default='home', max_length=50, verbose_name='Хуудас')),
                ('is_active', models.BooleanField(default=True, help_text='Вэб дээр харуулах эсэх', verbose_name='Идэвхтэй')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Шинэчилсэн')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Шинэчилсэн хэрэглэгч')),
            ],
            options={
                'verbose_name': 'Хуудасны агуулга',
                'verbose_name_plural': 'Хуудасны агуулгууд',
                'ordering': ['page', 'key'],
            },
        ),
    ]
