# Generated by Django 6.0 on 2026-01-17 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_pagecontent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagecontent',
            options={'ordering': ['page', 'key'], 'permissions': [('can_edit_content', 'Хуудасны агуулга засах эрхтэй')], 'verbose_name': 'Хуудасны агуулга', 'verbose_name_plural': 'Хуудасны агуулгууд'},
        ),
    ]
