# Generated by Django 6.0 on 2026-01-17 07:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_pagecontent_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecontent',
            name='content',
            field=ckeditor.fields.RichTextField(help_text='Вэб дээр харагдах текст (HTML форматчлалтай)', verbose_name='Агуулга'),
        ),
    ]
