# Generated by Django 6.0 on 2026-01-31 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_pagecontent_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('PRESIDENT', 'Тэргүүн'), ('DIRECTOR', 'Захирал'), ('MANAGER', 'Менежер'), ('ACCOUNTANT', 'Нягтлан'), ('TEACHER_BEGINNER', 'Анхан шатны багш'), ('TEACHER_INTERMEDIATE', 'Дунд шатны багш'), ('TEACHER_ADVANCED', 'Дээд шатны багш'), ('STUDENT', 'Сурагч')], default='STUDENT', max_length=30, verbose_name='Эрх'),
        ),
    ]
