# Generated by Django 6.0 on 2026-01-31 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_userprofile_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Ангиллын нэр')),
                ('description', models.TextField(blank=True, verbose_name='Тайлбар')),
                ('is_active', models.BooleanField(default=True, verbose_name='Идэвхтэй эсэх')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Үүсгэсэн огноо')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='main.productcategory', verbose_name='Эцэг ангилал')),
            ],
            options={
                'verbose_name': 'Бүтээгдэхүүний ангилал',
                'verbose_name_plural': 'Бүтээгдэхүүний ангиллууд',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Барааны код/SKU')),
                ('name', models.CharField(max_length=200, verbose_name='Бүтээгдэхүүний нэр')),
                ('description', models.TextField(blank=True, verbose_name='Тайлбар')),
                ('purchase_price', models.DecimalField(decimal_places=2, help_text='Нийлүүлэгчээс авах үнэ', max_digits=12, verbose_name='Худалдан авах үнэ')),
                ('selling_price', models.DecimalField(decimal_places=2, help_text='Үйлчлүүлэгчид зарах үнэ', max_digits=12, verbose_name='Борлуулах үнэ')),
                ('unit', models.CharField(choices=[('PIECE', 'Ширхэг'), ('BOX', 'Хайрцаг'), ('PACK', 'Багц'), ('KG', 'Кг'), ('LITER', 'Литр'), ('METER', 'Метр'), ('SET', 'Иж бүрдэл')], default='PIECE', max_length=20, verbose_name='Хэмжих нэгж')),
                ('current_stock', models.IntegerField(default=0, verbose_name='Одоогийн үлдэгдэл')),
                ('min_stock', models.IntegerField(default=0, help_text='Сануулга өгөх үлдэгдэл', verbose_name='Доод үлдэгдэл')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Зураг')),
                ('supplier', models.CharField(blank=True, max_length=200, verbose_name='Нийлүүлэгч')),
                ('supplier_contact', models.CharField(blank=True, max_length=100, verbose_name='Холбоо барих')),
                ('is_active', models.BooleanField(default=True, verbose_name='Идэвхтэй эсэх')),
                ('notes', models.TextField(blank=True, verbose_name='Тэмдэглэл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Үүсгэсэн огноо')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Шинэчилсэн огноо')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_products', to=settings.AUTH_USER_MODEL, verbose_name='Үүсгэсэн хэрэглэгч')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='main.productcategory', verbose_name='Ангилал')),
            ],
            options={
                'verbose_name': 'Бүтээгдэхүүн',
                'verbose_name_plural': 'Бүтээгдэхүүнүүд',
                'ordering': ['-created_at'],
                'permissions': [('can_view_inventory', 'Бараа материал харах эрхтэй'), ('can_manage_inventory', 'Бараа материал удирдах эрхтэй')],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', 'Орлого'), ('OUT', 'Зарлага'), ('ADJUSTMENT', 'Тохируулга'), ('RETURN', 'Буцаалт')], max_length=20, verbose_name='Төрөл')),
                ('quantity', models.IntegerField(verbose_name='Тоо ширхэг')),
                ('price', models.DecimalField(decimal_places=2, help_text='Орлого бол худалдан авах үнэ, зарлага бол борлуулах үнэ', max_digits=12, verbose_name='Нэгж үнэ')),
                ('total_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='Нийт дүн')),
                ('reference_number', models.CharField(blank=True, max_length=100, verbose_name='Баримтын дугаар')),
                ('customer_name', models.CharField(blank=True, max_length=200, verbose_name='Үйлчлүүлэгч/Нийлүүлэгч')),
                ('notes', models.TextField(blank=True, verbose_name='Тэмдэглэл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Огноо')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Бүртгэсэн хэрэглэгч')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='main.product', verbose_name='Бүтээгдэхүүн')),
            ],
            options={
                'verbose_name': 'Агуулахын хөдөлгөөн',
                'verbose_name_plural': 'Агуулахын хөдөлгөөнүүд',
                'ordering': ['-created_at'],
            },
        ),
    ]
