# Generated by Django 6.0 on 2026-01-31 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_productcategory_product_stockmovement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Дансны нэр')),
                ('account_type', models.CharField(choices=[('CASH', 'Касс'), ('BANK', 'Банкны данс'), ('CARD', 'Картын данс')], max_length=20, verbose_name='Төрөл')),
                ('account_number', models.CharField(blank=True, max_length=100, verbose_name='Дансны дугаар')),
                ('bank_name', models.CharField(blank=True, max_length=200, verbose_name='Банкны нэр')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Үлдэгдэл')),
                ('is_active', models.BooleanField(default=True, verbose_name='Идэвхтэй эсэх')),
                ('notes', models.TextField(blank=True, verbose_name='Тэмдэглэл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Үүсгэсэн огноо')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Шинэчилсэн огноо')),
            ],
            options={
                'verbose_name': 'Данс',
                'verbose_name_plural': 'Дансууд',
                'ordering': ['account_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Нэр')),
                ('counterparty_type', models.CharField(choices=[('SUPPLIER', 'Нийлүүлэгч'), ('CUSTOMER', 'Үйлчлүүлэгч'), ('BOTH', 'Хоёулаа')], default='BOTH', max_length=20, verbose_name='Төрөл')),
                ('contact_person', models.CharField(blank=True, max_length=200, verbose_name='Холбоо барих хүн')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Утас')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Имэйл')),
                ('address', models.TextField(blank=True, verbose_name='Хаяг')),
                ('registration_number', models.CharField(blank=True, max_length=50, verbose_name='Регистрийн дугаар')),
                ('tax_number', models.CharField(blank=True, max_length=50, verbose_name='Татварын дугаар')),
                ('balance', models.DecimalField(decimal_places=2, default=0, help_text='Эерэг = Манай өр, Сөрөг = Тэдний өр', max_digits=15, verbose_name='Харилцах үлдэгдэл')),
                ('is_active', models.BooleanField(default=True, verbose_name='Идэвхтэй эсэх')),
                ('notes', models.TextField(blank=True, verbose_name='Тэмдэглэл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Үүсгэсэн огноо')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Шинэчилсэн огноо')),
            ],
            options={
                'verbose_name': 'Харилцагч',
                'verbose_name_plural': 'Харилцагчид',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_number', models.CharField(max_length=100, unique=True, verbose_name='Худалдан авалтын дугаар')),
                ('purchase_date', models.DateField(verbose_name='Огноо')),
                ('status', models.CharField(choices=[('DRAFT', 'Ноорог'), ('ORDERED', 'Захиалсан'), ('RECEIVED', 'Хүлээн авсан'), ('PAID', 'Төлсөн'), ('COMPLETED', 'Дууссан'), ('CANCELLED', 'Цуцалсан')], default='DRAFT', max_length=20, verbose_name='Төлөв')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Нийт дүн')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Төлсөн дүн')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Төлсөн огноо')),
                ('notes', models.TextField(blank=True, verbose_name='Тэмдэглэл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Үүсгэсэн огноо')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Шинэчилсэн огноо')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Үүсгэсэн хэрэглэгч')),
                ('payment_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.account', verbose_name='Төлбөрийн данс')),
                ('supplier', models.ForeignKey(limit_choices_to={'counterparty_type__in': ['SUPPLIER', 'BOTH']}, on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='main.counterparty', verbose_name='Нийлүүлэгч')),
            ],
            options={
                'verbose_name': 'Худалдан авалт',
                'verbose_name_plural': 'Худалдан авалтууд',
                'ordering': ['-purchase_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Тоо ширхэг')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Нэгж үнэ')),
                ('total_price', models.DecimalField(decimal_places=2, editable=False, max_digits=15, verbose_name='Нийт үнэ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.product', verbose_name='Бүтээгдэхүүн')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.purchase', verbose_name='Худалдан авалт')),
            ],
            options={
                'verbose_name': 'Худалдан авалтын зүйл',
                'verbose_name_plural': 'Худалдан авалтын зүйлүүд',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_number', models.CharField(max_length=100, unique=True, verbose_name='Борлуулалтын дугаар')),
                ('sale_date', models.DateField(verbose_name='Огноо')),
                ('status', models.CharField(choices=[('DRAFT', 'Ноорог'), ('CONFIRMED', 'Баталсан'), ('DELIVERED', 'Хүргэсэн'), ('PAID', 'Төлсөн'), ('COMPLETED', 'Дууссан'), ('CANCELLED', 'Цуцалсан')], default='DRAFT', max_length=20, verbose_name='Төлөв')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Нийт дүн')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Төлсөн дүн')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Төлсөн огноо')),
                ('notes', models.TextField(blank=True, verbose_name='Тэмдэглэл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Үүсгэсэн огноо')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Шинэчилсэн огноо')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Үүсгэсэн хэрэглэгч')),
                ('customer', models.ForeignKey(blank=True, limit_choices_to={'counterparty_type__in': ['CUSTOMER', 'BOTH']}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='main.counterparty', verbose_name='Үйлчлүүлэгч')),
                ('payment_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.account', verbose_name='Төлбөрийн данс')),
            ],
            options={
                'verbose_name': 'Борлуулалт',
                'verbose_name_plural': 'Борлуулалтууд',
                'ordering': ['-sale_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Тоо ширхэг')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Нэгж үнэ')),
                ('total_price', models.DecimalField(decimal_places=2, editable=False, max_digits=15, verbose_name='Нийт үнэ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.product', verbose_name='Бүтээгдэхүүн')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.sale', verbose_name='Борлуулалт')),
            ],
            options={
                'verbose_name': 'Борлуулалтын зүйл',
                'verbose_name_plural': 'Борлуулалтын зүйлүүд',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('INCOME', 'Орлого'), ('EXPENSE', 'Зарлага'), ('TRANSFER', 'Шилжүүлэг')], max_length=20, verbose_name='Төрөл')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Дүн')),
                ('description', models.CharField(max_length=500, verbose_name='Утга')),
                ('reference_number', models.CharField(blank=True, max_length=100, verbose_name='Баримтын дугаар')),
                ('transaction_date', models.DateField(verbose_name='Огноо')),
                ('notes', models.TextField(blank=True, verbose_name='Тэмдэглэл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Үүсгэсэн огноо')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='main.account', verbose_name='Данс')),
                ('counterparty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='main.counterparty', verbose_name='Харилцагч')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Үүсгэсэн хэрэглэгч')),
                ('related_purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.purchase', verbose_name='Худалдан авалт')),
                ('related_sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.sale', verbose_name='Борлуулалт')),
                ('to_account', models.ForeignKey(blank=True, help_text='Зөвхөн шилжүүлэг үед', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='main.account', verbose_name='Хүлээн авах данс')),
            ],
            options={
                'verbose_name': 'Гүйлгээ',
                'verbose_name_plural': 'Гүйлгээнүүд',
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
    ]
