# Generated by Django 6.0 on 2026-01-31 23:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_account_counterparty_purchase_purchaseitem_sale_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartOfAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Дансны код')),
                ('name', models.CharField(max_length=255, verbose_name='Дансны нэр')),
                ('account_type', models.CharField(choices=[('ASSET', 'Актив'), ('LIABILITY', 'Пассив'), ('EQUITY', 'Өмч'), ('INCOME', 'Орлого'), ('EXPENSE', 'Зардал'), ('COST', 'Өртөг')], max_length=20, verbose_name='Төрөл')),
                ('is_active', models.BooleanField(default=True, verbose_name='Идэвхтэй эсэх')),
                ('description', models.TextField(blank=True, verbose_name='Тайлбар')),
                ('debit_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Дебит үлдэгдэл')),
                ('credit_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Кредит үлдэгдэл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Үүссэн огноо')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Шинэчилсэн огноо')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='main.chartofaccounts', verbose_name='Дээд данс')),
            ],
            options={
                'verbose_name': 'Дансны төлөвлөгөө',
                'verbose_name_plural': 'Дансны төлөвлөгөө',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='AccountingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(verbose_name='Гүйлгээний огноо')),
                ('entry_number', models.CharField(max_length=50, unique=True, verbose_name='Гүйлгээний дугаар')),
                ('description', models.TextField(verbose_name='Гүйлгээний утга')),
                ('debit_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Дебит дүн')),
                ('credit_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Кредит дүн')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Үүссэн огноо')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Үүсгэсэн хэрэглэгч')),
                ('credit_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_entries', to='main.chartofaccounts', verbose_name='Кредит данс')),
                ('debit_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debit_entries', to='main.chartofaccounts', verbose_name='Дебит данс')),
            ],
            options={
                'verbose_name': 'Гүйлгээний бичилт',
                'verbose_name_plural': 'Гүйлгээний бичилтүүд',
                'ordering': ['-entry_date', '-entry_number'],
            },
        ),
    ]
