# Generated by Django 6.0 on 2026-02-02 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_chartofaccounts_accountingentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(choices=[('KHAN', 'Хаан банк'), ('GOLOMT', 'Голомт банк'), ('TDB', 'Худалдаа хөгжлийн банк'), ('STATE', 'Төрийн банк'), ('OTHER', 'Бусад')], max_length=50, verbose_name='Банкны нэр')),
                ('transaction_date', models.DateField(verbose_name='Гүйлгээний огноо')),
                ('transaction_time', models.TimeField(blank=True, null=True, verbose_name='Гүйлгээний цаг')),
                ('description', models.TextField(verbose_name='Гүйлгээний утга')),
                ('counterparty_account', models.CharField(blank=True, max_length=100, verbose_name='Харьцсан данс')),
                ('counterparty_name', models.CharField(blank=True, max_length=255, verbose_name='Харьцсан дансны нэр')),
                ('income_amount', models.DecimalField(decimal_places=2, default=0, help_text='Данс руу орсон дүн', max_digits=15, verbose_name='Орлого')),
                ('expense_amount', models.DecimalField(decimal_places=2, default=0, help_text='Дансаас гарсан дүн', max_digits=15, verbose_name='Зарлага')),
                ('opening_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Эхний үлдэгдэл')),
                ('closing_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Эцсийн үлдэгдэл')),
                ('branch_code', models.CharField(blank=True, max_length=20, verbose_name='Салбарын код')),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Ханш')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Боловсруулсан эсэх')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='Импортолсон огноо')),
                ('accounting_entry', models.ForeignKey(blank=True, help_text='Үүссэн журналын бичилт', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.accountingentry', verbose_name='Гүйлгээний бичилт')),
                ('bank_account', models.ForeignKey(help_text='Дансны төлөвлөгөөний банкны данс (110x)', on_delete=django.db.models.deletion.PROTECT, to='main.chartofaccounts', verbose_name='Банкны данс')),
                ('counterparty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.counterparty', verbose_name='Харилцагч')),
                ('imported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Импортолсон хэрэглэгч')),
            ],
            options={
                'verbose_name': 'Банкны гүйлгээ',
                'verbose_name_plural': 'Банкны гүйлгээнүүд',
                'ordering': ['-transaction_date', '-transaction_time'],
                'indexes': [models.Index(fields=['bank_account', 'transaction_date'], name='main_banktr_bank_ac_31882e_idx'), models.Index(fields=['is_processed'], name='main_banktr_is_proc_d7cd07_idx')],
            },
        ),
    ]
