# Generated by Django 6.0 on 2026-02-02 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_banktransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='offset_account',
            field=models.ForeignKey(blank=True, help_text='Орлого бол кредит данс (4xxx), зарлага бол дебит данс (5xxx)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_transactions_offset', to='main.chartofaccounts', verbose_name='Эсрэг данс'),
        ),
        migrations.AddField(
            model_name='counterparty',
            name='default_expense_account',
            field=models.ForeignKey(blank=True, help_text='Энэ харилцагч руу зарлага гарахдаа ашиглах данс (5xxx)', limit_choices_to={'account_type': 'EXPENSE', 'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counterparty_expense', to='main.chartofaccounts', verbose_name='Зардлын данс'),
        ),
        migrations.AddField(
            model_name='counterparty',
            name='default_income_account',
            field=models.ForeignKey(blank=True, help_text='Энэ харилцагчаас орлого орохдоо ашиглах данс (4xxx)', limit_choices_to={'account_type': 'INCOME', 'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counterparty_income', to='main.chartofaccounts', verbose_name='Орлогын данс'),
        ),
    ]
