# Generated by Django 6.0 on 2026-02-02 15:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_banktransaction_offset_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='schedule',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Хуваарь'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=8, validators=[django.core.validators.RegexValidator(message='Утасны дугаар 8 оронтой тоо байх ёстой', regex='^\\d{8}$')], verbose_name='Утас'),
        ),
    ]
