# Generated by Django 6.0 on 2026-02-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_course_schedule_alter_userprofile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartofaccounts',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Систем ашиглаж эхлэхээс өмнөх үлдэгдэл', max_digits=15, verbose_name='Эхний үлдэгдэл'),
        ),
    ]
