# Generated by Django 6.0 on 2026-02-06 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_chartofaccounts_opening_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='income_month',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Хэддүгээр сарын төлбөр (1-12)', null=True, verbose_name='Төлбөрийн сар'),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='income_sale',
            field=models.ForeignKey(blank=True, help_text='Барааны борлуулалт бол холбогдох борлуулалтын бүртгэл', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.sale', verbose_name='Борлуулалт'),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='income_student',
            field=models.ForeignKey(blank=True, help_text='Сурагчийн төлбөр бол ямар сурагч', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.userprofile', verbose_name='Сурагч'),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='income_type',
            field=models.CharField(blank=True, choices=[('STUDENT_PAYMENT', 'Сурагчийн төлбөр'), ('PRODUCT_SALE', 'Барааны борлуулалт'), ('SERVICE_FEE', 'Үйлчилгээний төлбөр'), ('DONATION', 'Хандив'), ('OTHER', 'Бусад орлого')], help_text='Орлогын гүйлгээний төрөл', max_length=50, null=True, verbose_name='Орлогын төрөл'),
        ),
    ]
