# Generated by Django 6.0 on 2026-02-07 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_banktransaction_income_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='payment_color',
            field=models.CharField(blank=True, default='', help_text='Төлбөрийн нүдний өнгө (жишээ: #ff0000)', max_length=7, verbose_name='Өнгө'),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='payment_comment',
            field=models.TextField(blank=True, help_text='Төлбөрийн тухай тэмдэглэл, анхааруулга', verbose_name='Тэмдэглэл'),
        ),
    ]
