# Generated by Django 6.0 on 2026-02-07 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_banktransaction_payment_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashFlowIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Жишээ: 1.1.1', max_length=10, unique=True, verbose_name='Код')),
                ('name', models.CharField(help_text='Үзүүлэлтийн нэр', max_length=255, verbose_name='Нэр')),
                ('flow_type', models.CharField(choices=[('INCOME', 'Орлого'), ('EXPENSE', 'Зарлага'), ('BOTH', 'Хоёулаа')], help_text='Орлого эсвэл зарлага', max_length=10, verbose_name='Төрөл')),
                ('level', models.PositiveSmallIntegerField(default=1, help_text='Үзүүлэлтийн түвшин (1, 2, 3...)', verbose_name='Түвшин')),
                ('is_active', models.BooleanField(default=True, verbose_name='Идэвхтэй')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Эрэмбэ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Үүсгэсэн огноо')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Шинэчилсэн огноо')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='main.cashflowindicator', verbose_name='Эцэг үзүүлэлт')),
            ],
            options={
                'verbose_name': 'Мөнгөн гүйлгээний үзүүлэлт',
                'verbose_name_plural': 'Мөнгөн гүйлгээний үзүүлэлтүүд',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='cash_flow_indicator',
            field=models.ForeignKey(blank=True, help_text='Мөнгөн гүйлгээний тайланд ямар үзүүлэлтэнд хамаарах', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.cashflowindicator', verbose_name='Мөнгөн гүйлгээний үзүүлэлт'),
        ),
    ]
