# Generated by Django 6.0 on 2026-02-07 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_cashflowindicator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='income_course',
            field=models.ForeignKey(blank=True, help_text='Сурагчийн төлбөр бол ямар анги', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.course', verbose_name='Анги'),
        ),
    ]
