# Generated by Django 6.0 on 2026-02-07 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_banktransaction_income_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(help_text='Хэддүгээр сарын төлбөр (1-12)', verbose_name='Сар')),
                ('year', models.PositiveSmallIntegerField(help_text='Хэддүгээр оны төлбөр (жишээ: 2026)', verbose_name='Он')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Энэ сурагч/сар/анги-д хуваарилсан дүн', max_digits=15, verbose_name='Дүн')),
                ('comment', models.TextField(blank=True, verbose_name='Тэмдэглэл')),
                ('color', models.CharField(blank=True, default='', max_length=7, verbose_name='Өнгө')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course', verbose_name='Анги')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, to='main.userprofile', verbose_name='Сурагч')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='main.banktransaction', verbose_name='Банкны гүйлгээ')),
            ],
            options={
                'verbose_name': 'Төлбөрийн хуваарилалт',
                'verbose_name_plural': 'Төлбөрийн хуваарилалтууд',
                'ordering': ['transaction', 'student', 'year', 'month'],
            },
        ),
    ]
