# Generated by Django 6.0 on 2026-02-08 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_paymentallocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='account_type',
            field=models.CharField(choices=[('BANK', 'Банк'), ('CASH', 'Касс')], default='BANK', help_text='Банкны данс эсвэл касс', max_length=10, verbose_name='Дансны төрөл'),
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='bank_account',
            field=models.ForeignKey(help_text='Дансны төлөвлөгөөний банк/кассын данс (110x, 101x)', on_delete=django.db.models.deletion.PROTECT, to='main.chartofaccounts', verbose_name='Данс'),
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='bank_name',
            field=models.CharField(choices=[('KHAN', 'Хаан банк'), ('GOLOMT', 'Голомт банк'), ('TDB', 'Худалдаа хөгжлийн банк'), ('STATE', 'Төрийн банк'), ('CASH_REGISTER', 'Касс'), ('OTHER', 'Бусад')], max_length=50, verbose_name='Банк/Кассын нэр'),
        ),
    ]
