# Generated by Django 6.0 on 2026-02-08 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_banktransaction_account_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='expense_type',
            field=models.CharField(blank=True, choices=[('PRODUCT_PURCHASE', 'Бараа материалын худалдан авалт'), ('SALARY', 'Цалин'), ('RENT', 'Түрээс'), ('UTILITIES', 'Ахуйн зардал (цахилгаан, ус гэх мэт)'), ('MARKETING', 'Сурталчилгаа'), ('OFFICE_SUPPLIES', 'Оффисын хэрэгсэл'), ('TRANSPORTATION', 'Тээвэр'), ('OTHER', 'Бусад зардал')], help_text='Зарлагын гүйлгээний төрөл', max_length=50, null=True, verbose_name='Зарлагын төрөл'),
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='bank_account',
            field=models.ForeignKey(help_text='Дансны төлөвлөгөөний банк (110x) эсвэл касс (100x, 101x) данс', on_delete=django.db.models.deletion.PROTECT, to='main.chartofaccounts', verbose_name='Данс'),
        ),
    ]
