# Generated by Django 6.0 on 2026-02-09 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_banktransaction_expense_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='accounting_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='main.accountingentry', verbose_name='Журналын бичилт'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='bank_account',
            field=models.ForeignKey(blank=True, help_text='1001-Касс эсвэл 1101-Банк', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements_account', to='main.chartofaccounts', verbose_name='Касс/Данс'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='counterparty',
            field=models.ForeignKey(blank=True, help_text='Нийлүүлэгч эсвэл үйлчлүүлэгч', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='main.counterparty', verbose_name='Харилцагч'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'Бэлэн'), ('BANK', 'Данс'), ('CREDIT', 'Зээлээр')], help_text='Бэлэн, данс эсвэл зээлээр', max_length=20, verbose_name='Төлбөрийн хэлбэр'),
        ),
    ]
