# Generated by Django 6.0 on 2026-02-09 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_stockmovement_accounting_entry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='purchase_number',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Худалдан авалтын дугаар'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_number',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Борлуулалтын дугаар'),
        ),
    ]
