# Generated by Django 6.0 on 2026-02-09 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_purchase_purchase_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='supplier_fk',
            field=models.ForeignKey(blank=True, limit_choices_to={'counterparty_type__in': ['SUPPLIER', 'BOTH']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplied_products', to='main.counterparty', verbose_name='Нийлүүлэгч'),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.CharField(blank=True, max_length=200, verbose_name='Нийлүүлэгч (хуучин)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier_contact',
            field=models.CharField(blank=True, max_length=100, verbose_name='Холбоо барих (хуучин)'),
        ),
    ]
