# Generated by Django 6.0 on 2026-02-10 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_product_supplier_fk_alter_product_supplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Нэр'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Овог'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mongolian_name',
            field=models.CharField(blank=True, help_text='Овог + Нэр-ээр орлогдлоо', max_length=200, verbose_name='Монгол нэр (хуучин)'),
        ),
    ]
