# Generated by Django 6.0 on 2026-02-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_userprofile_first_name_userprofile_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Эрэгтэй'), ('F', 'Эмэгтэй'), ('O', 'Бусад')], max_length=10, null=True, verbose_name='Хүйс'),
        ),
    ]
