# Generated by Django 6.0 on 2026-02-11 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_userprofile_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='current_stock',
        ),
        migrations.AddField(
            model_name='product',
            name='initial_stock',
            field=models.IntegerField(default=0, help_text='Гараас оруулах эхний үлдэгдэл', verbose_name='Эхний үлдэгдэл'),
        ),
    ]
