# Generated by Django 6.0 on 2026-02-12 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_remove_product_current_stock_product_initial_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='current_job',
            field=models.CharField(blank=True, max_length=200, verbose_name='Одоо эрхэлж буй ажил'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='education',
            field=models.CharField(blank=True, max_length=200, verbose_name='Боловсрол'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='facebook_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Facebook нэр'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profession',
            field=models.CharField(blank=True, max_length=200, verbose_name='Мэргэжил'),
        ),
    ]
