# Generated by Django 6.0 on 2026-02-12 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_userprofile_current_job_userprofile_education_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='salesperson',
            field=models.ForeignKey(blank=True, help_text='Борлуулалт хийсэн менежер/ажилтан', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_made', to=settings.AUTH_USER_MODEL, verbose_name='Борлуулагч'),
        ),
    ]
