# Generated by Django 6.0 on 2026-02-28 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_stockmovement_salesperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='expected_payment_method',
            field=models.CharField(blank=True, help_text='Касс / Харилцах / Хоёулаа - Excel-ээс импортлосон мэдээлэл', max_length=20, verbose_name='Төлбөрийн хэлбэр (таамаглал)'),
        ),
        migrations.AddField(
            model_name='sale',
            name='import_ref',
            field=models.CharField(blank=True, help_text='Excel импортын давхардлаас сэргийлэх лавлагаа', max_length=200, verbose_name='Импортын лавлагаа'),
        ),
        migrations.AddField(
            model_name='sale',
            name='salesperson_name',
            field=models.CharField(blank=True, help_text='Борлуулалт буюу төлбөр хүлээн авсан ажилтны нэр', max_length=200, verbose_name='Хүлээн авсан хүн'),
        ),
    ]
