# Generated by Django 6.0 on 2026-04-09 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_sale_add_salesperson_import_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('BEGINNER_1', 'Анхан 1'), ('BEGINNER_2', 'Анхан 2'), ('INTERMEDIATE', 'Дунд'), ('ADVANCED', 'Ахисан'), ('VIP', 'VIP')], max_length=20, verbose_name='Түвшин'),
        ),
    ]
