# Generated by Django 6.0 on 2026-04-09 04:47

from django.db import migrations


def migrate_course_levels(apps, schema_editor):
    """Хичээлийн түвшнийг хуучин форматаас шинэ форматад хөрвүүлэх"""
    Course = apps.get_model('main', 'Course')
    
    # BEGINNER түвшнийн хичээлүүдийг нэрээр ялгаж шинэ түвшинд хөрвүүлэх
    for course in Course.objects.filter(level='BEGINNER'):
        if '2' in course.name:
            course.level = 'BEGINNER_2'
        else:
            course.level = 'BEGINNER_1'
        course.save()
    
    # Бусад түвшнүүд утгатай байхгүй (INTERMEDIATE ба ADVANCED үлдэж байна)
    print("✓ Хичээлийн түвшний утгаүүд шинэчилэгдсэн")


def reverse_migrate_course_levels(apps, schema_editor):
    """Хөрвүүлэлтийг буцаах"""
    Course = apps.get_model('main', 'Course')
    
    # BEGINNER_1 ба BEGINNER_2-ийг BEGINNER рүү буцаах
    Course.objects.filter(level__in=['BEGINNER_1', 'BEGINNER_2']).update(level='BEGINNER')
    print("✓ Хичээлийн түвшний хөрвүүлэлт буцагдсан")


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_course_level'),
    ]

    operations = [
        migrations.RunPython(migrate_course_levels, reverse_migrate_course_levels),
    ]
