# Generated by Django 6.0.3 on 2026-04-09 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_migrate_course_levels_to_v2'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalePaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Энэ гүйлгээнээс тухайн борлуулалтад холбосон дүн', max_digits=15, verbose_name='Холбосон дүн')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_allocations', to='main.sale', verbose_name='Борлуулалт')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_allocations', to='main.banktransaction', verbose_name='Банкны гүйлгээ')),
            ],
            options={
                'verbose_name': 'Борлуулалтын төлбөрийн хуваарилалт',
                'verbose_name_plural': 'Борлуулалтын төлбөрийн хуваарилалтууд',
                'ordering': ['-created_at'],
                'unique_together': {('transaction', 'sale')},
            },
        ),
    ]
