# Generated by Django 6.0.3 on 2026-04-12 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_salepaymentallocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceWeekdayTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekdays', models.CharField(max_length=20, verbose_name='Гаригууд')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_weekday_template', to='main.course', verbose_name='Сургалт')),
            ],
            options={
                'verbose_name': 'Ирцийн гаригийн загвар',
                'verbose_name_plural': 'Ирцийн гаригийн загварууд',
            },
        ),
    ]
