# Generated by Django 6.0.3 on 2026-04-12 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_attendanceweekdaytemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='teacher_levels',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Зааж буй түвшин'),
        ),
    ]
