# Generated by Django 6.0.3 on 2026-04-12 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_teacher_levels'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceTeacherSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_ids', models.TextField(blank=True, default='', verbose_name='Багшийн ID жагсаалт')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_teacher_selection', to='main.course', verbose_name='Сургалт')),
            ],
            options={
                'verbose_name': 'Ирцийн багшийн сонголт',
                'verbose_name_plural': 'Ирцийн багшийн сонголтууд',
            },
        ),
        migrations.CreateModel(
            name='TeacherAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Огноо')),
                ('present', models.BooleanField(default=True, verbose_name='Заасан')),
                ('notes', models.TextField(blank=True, verbose_name='Тэмдэглэл')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_attendances', to='main.course', verbose_name='Сургалт')),
                ('teacher', models.ForeignKey(limit_choices_to={'role__in': ['TEACHER_BEGINNER', 'TEACHER_INTERMEDIATE', 'TEACHER_ADVANCED']}, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_attendances', to='main.userprofile', verbose_name='Багш')),
            ],
            options={
                'verbose_name': 'Багшийн ирц',
                'verbose_name_plural': 'Багшийн ирцүүд',
                'ordering': ['-date', 'teacher__last_name', 'teacher__first_name'],
                'unique_together': {('course', 'teacher', 'date')},
            },
        ),
    ]
