# Generated by Django 6.0.3 on 2026-04-12 04:15

import django.db.models.deletion
from django.db import migrations, models


def copy_existing_course_teachers(apps, schema_editor):
    Course = apps.get_model('main', 'Course')
    CourseTeacherAssignment = apps.get_model('main', 'CourseTeacherAssignment')

    assignments = []
    for course in Course.objects.exclude(teacher_id__isnull=True):
        assignments.append(
            CourseTeacherAssignment(course_id=course.id, teacher_id=course.teacher_id)
        )

    if assignments:
        CourseTeacherAssignment.objects.bulk_create(assignments, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_teacher_attendance_rows'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTeacherAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='main.course', verbose_name='Сургалт')),
                ('teacher', models.ForeignKey(limit_choices_to={'role__in': ['TEACHER_BEGINNER', 'TEACHER_INTERMEDIATE', 'TEACHER_ADVANCED']}, on_delete=django.db.models.deletion.CASCADE, related_name='course_assignments', to='main.userprofile', verbose_name='Багш')),
            ],
            options={
                'verbose_name': 'Ангийн багшийн холбоос',
                'verbose_name_plural': 'Ангийн багшийн холбоосууд',
                'ordering': ['course__name', 'teacher__last_name', 'teacher__first_name'],
                'unique_together': {('course', 'teacher')},
            },
        ),
        migrations.RunPython(copy_existing_course_teachers, migrations.RunPython.noop),
    ]
