# Generated by Django 6.0.3 on 2026-04-29 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_course_teacher_assignments'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankTransactionSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Дүн')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Тайлбар')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.chartofaccounts', verbose_name='Данс')),
                ('accounting_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='split_source', to='main.accountingentry', verbose_name='Журналын бичилт')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_splits', to='main.banktransaction', verbose_name='Банкны гүйлгээ')),
            ],
            options={
                'verbose_name': 'Гүйлгээний нэмэлт хуваарилалт',
                'verbose_name_plural': 'Гүйлгээний нэмэлт хуваарилалтууд',
                'ordering': ['id'],
            },
        ),
    ]
