# Generated by Django 6.0.3 on 2026-04-29 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_banktransactionsplit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'Бэлэн'), ('BANK', 'Данс'), ('BANK_PENDING', 'Харилцах (хожим)'), ('CREDIT', 'Зээлээр')], help_text='Бэлэн, данс эсвэл зээлээр', max_length=20, verbose_name='Төлбөрийн хэлбэр'),
        ),
        migrations.CreateModel(
            name='SaleExtraSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Дүн')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Тайлбар')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.chartofaccounts', verbose_name='Данс')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_splits', to='main.sale', verbose_name='Борлуулалт')),
            ],
            options={
                'verbose_name': 'Борлуулалтын нэмэлт хуваарилалт',
                'verbose_name_plural': 'Борлуулалтын нэмэлт хуваарилалтууд',
                'ordering': ['id'],
            },
        ),
    ]
