# Generated by Django 6.0 on 2026-08-11 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_saleextrasplit'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=200, verbose_name='Нэр')),
            ],
            options={
                'verbose_name': 'Орлогын төрөл',
                'verbose_name_plural': 'Орлогын төрөлүүд',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='saleextrasplit',
            name='account',
        ),
        migrations.RemoveField(
            model_name='saleextrasplit',
            name='sale',
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'Бэлэн'), ('BANK', 'Данс'), ('CREDIT', 'Зээлээр')], help_text='Бэлэн, данс эсвэл зээлээр', max_length=20, verbose_name='Төлбөрийн хэлбэр'),
        ),
        migrations.DeleteModel(
            name='BankTransactionSplit',
        ),
        migrations.DeleteModel(
            name='SaleExtraSplit',
        ),
    ]
