# Generated by Django 6.0.3 on 2026-08-12 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_add_internal_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='expense_accounting_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_sales', to='main.accountingentry', verbose_name='Зардлын журналын бичилт'),
        ),
    ]
