# Generated by Django 6.0.3 on 2026-08-12 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_add_stockmovement_sale_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingentry',
            name='related_sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_entries', to='main.sale', verbose_name='Борлуулалт'),
        ),
    ]
