# Generated by Django 6.0.3 on 2026-08-24 03:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_add_banktransaction_transfer_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankTransferLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Дүн')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Үүсгэсэн огноо')),
                ('accounting_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_transfer_link', to='main.accountingentry', verbose_name='Журналын бичилт')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Үүсгэсэн хэрэглэгч')),
                ('expense_transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_link_as_expense', to='main.banktransaction', verbose_name='Зарлагын гүйлгээ')),
                ('income_transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_link_as_income', to='main.banktransaction', verbose_name='Орлогын гүйлгээ')),
            ],
            options={
                'verbose_name': 'Харилцах хоорондын шилжүүлэг',
                'verbose_name_plural': 'Харилцах хоорондын шилжүүлгүүд',
            },
        ),
    ]
