# Generated by Django 6.0 on 2026-09-17 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_banktransferlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('BEGINNER_1', '1'), ('BEGINNER_2', '2'), ('INTERMEDIATE', '3'), ('ADVANCED', '4'), ('VIP', 'VIP')], max_length=20, verbose_name='Түвшин'),
        ),
    ]
