# Generated by Django 6.0 on 2026-09-17 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_alter_course_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='photo_filename',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Зургийн файлын нэр'),
        ),
    ]
