# Generated by Django 6.0.3 on 2026-09-29 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_userprofile_teacher_display_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='counterparty',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counterparty', to='main.userprofile', verbose_name='Холбогдсон хэрэглэгч'),
        ),
    ]
