# Generated by Django 6.0.3 on 2026-09-29 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_counterparty_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'Бэлэн'), ('BANK', 'Данс'), ('MIXED', 'Бэлэн + Данс'), ('CREDIT', 'Зээлээр'), ('INTERNAL', 'Дотоод хэрэгцээ')], help_text='Бэлэн, данс эсвэл зээлээр', max_length=20, verbose_name='Төлбөрийн хэлбэр'),
        ),
    ]
