# Generated by Django 6.0.3 on 2026-09-29 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_stockmovement_mixed_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='reference_number',
            field=models.CharField(blank=True, db_index=True, help_text='Банкны хуулгын гүйлгээний дугаар (давхардал шалгахад)', max_length=50, verbose_name='Гүйлгээний дугаар'),
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='bank_name',
            field=models.CharField(choices=[('KHAN', 'Хаан банк'), ('GOLOMT', 'Голомт банк'), ('TDB', 'Худалдаа хөгжлийн банк'), ('STATE', 'Төрийн банк'), ('XAC', 'Хас банк'), ('CASH_REGISTER', 'Касс'), ('OTHER', 'Бусад')], max_length=50, verbose_name='Банк/Кассын нэр'),
        ),
    ]
