# Generated by Django 6.0.3 on 2026-10-01 00:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_banktransaction_reference_xac'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('books_start_date', models.DateField(blank=True, help_text='Энэ өдрөөс эхэлсэн гүйлгээ шинэ үед орно. Хоосон бол бүх гүйлгээ тооцогдоно.', null=True, verbose_name='Систем эхлэх огноо')),
                ('legacy_opening_snapshot', models.JSONField(blank=True, default=dict, help_text='Шинэ үе эхлэхэд тэглэсэн хуучин эхний үлдэгдлүүд', verbose_name='Хуучин эхний үлдэгдэл (нөөц)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Санхүүгийн тохиргоо',
                'verbose_name_plural': 'Санхүүгийн тохиргоо',
            },
        ),
    ]
