# Generated by Django 6.0.3 on 2026-10-01 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_books_start_2026_09_30'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='pos_bank_account',
            field=models.ForeignKey(blank=True, help_text='POS картаар төлсөн бол аль банкны POS (сэттлмэнттэй тулгахад ашиглана)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_sales', to='main.chartofaccounts', verbose_name='POS-ын банк'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'Бэлэн'), ('BANK', 'Данс'), ('MIXED', 'Бэлэн + Данс'), ('CREDIT', 'Зээлээр'), ('INTERNAL', 'Дотоод хэрэгцээ'), ('POS', 'POS карт')], help_text='Бэлэн, данс эсвэл зээлээр', max_length=20, verbose_name='Төлбөрийн хэлбэр'),
        ),
    ]
