# Generated by Django 6.0.3 on 2026-10-01 02:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_sale_pos_bank'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoLinkRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Загварын нэр')),
                ('keywords', models.TextField(help_text='Таслал эсвэл шинэ мөрөөр тусгаарлана. Аль нэг нь утга/харилцагчийн нэрэнд байвал таарна (том/жижиг үсэг ялгахгүй).', verbose_name='Түлхүүр үгс')),
                ('direction', models.CharField(choices=[('EXPENSE', 'Зарлага'), ('INCOME', 'Орлого'), ('ANY', 'Аль аль нь')], default='EXPENSE', max_length=10, verbose_name='Чиглэл')),
                ('amount_min', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Дүн (доод)')),
                ('amount_max', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Дүн (дээд)')),
                ('income_type', models.CharField(blank=True, max_length=50, verbose_name='Орлогын төрөл')),
                ('auto_apply', models.BooleanField(default=False, help_text='Асаалттай бол хуулга импортлоход шалгалтгүйгээр холбогдоно (банкны шимтгэл гэх мэт найдвартай загварт).', verbose_name='Импортлох үед шууд холбох')),
                ('priority', models.PositiveIntegerField(default=100, help_text='Бага тоо нь түрүүлж шалгагдана', verbose_name='Эрэмбэ')),
                ('is_active', models.BooleanField(default=True, verbose_name='Идэвхтэй')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(blank=True, help_text='Хоосон бол бүх банк', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='main.chartofaccounts', verbose_name='Зөвхөн энэ банк')),
                ('cash_flow_indicator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='main.cashflowindicator', verbose_name='Мөнгөн гүйлгээний үзүүлэлт')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('offset_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='main.chartofaccounts', verbose_name='Эсрэг данс')),
            ],
            options={
                'verbose_name': 'Автомат холболтын загвар',
                'verbose_name_plural': 'Автомат холболтын загварууд',
                'ordering': ['priority', 'id'],
            },
        ),
    ]
