# Generated by Django 6.0.3 on 2026-10-01 04:04

from collections import Counter

from django.db import migrations, models


def seed_monthly_fee(apps, schema_editor):
    """Анги бүрийн сарын төлбөрийг бодит төлбөрийн хамгийн түгээмэл дүнгээр бөглөнө."""
    Course = apps.get_model('main', 'Course')
    PaymentAllocation = apps.get_model('main', 'PaymentAllocation')
    for course in Course.objects.all():
        amounts = Counter(PaymentAllocation.objects.filter(course=course).values_list('amount', flat=True))
        if amounts:
            course.monthly_fee = amounts.most_common(1)[0][0]
            course.save(update_fields=['monthly_fee'])


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0059_link_sale_effects'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='monthly_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Сурагчийн нэг сарын төлбөр — "Сурагчдын төлбөр" хуудсанд дутуу/бүрэн төлсөнийг тодорхойлно. 0 бол шалгахгүй.', max_digits=10, verbose_name='Сарын төлбөр (₮)'),
        ),
        migrations.RunPython(seed_monthly_fee, migrations.RunPython.noop),
    ]
