# Generated by Django 6.0.3 on 2026-10-03 06:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0060_course_monthly_fee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(verbose_name='Сар')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Он')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Дүн')),
                ('paid_date', models.DateField(verbose_name='Төлсөн огноо')),
                ('method', models.CharField(choices=[('BANK', 'Банкаар'), ('CASH', 'Бэлнээр'), ('OTHER', 'Бусад')], default='BANK', max_length=10, verbose_name='Төлсөн хэлбэр')),
                ('payer_name', models.CharField(blank=True, help_text='Хуулгатай тааруулахад ашиглана', max_length=255, verbose_name='Төлөгчийн нэр/данс')),
                ('comment', models.TextField(blank=True, verbose_name='Тэмдэглэл')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('allocation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_payment', to='main.paymentallocation', verbose_name='Холбогдсон хуваарилалт')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course', verbose_name='Анги')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Тэмдэглэсэн')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='pending_payments', to='main.userprofile', verbose_name='Сурагч')),
            ],
            options={
                'verbose_name': 'Хуулга хүлээж буй төлбөр',
                'verbose_name_plural': 'Хуулга хүлээж буй төлбөрүүд',
                'ordering': ['paid_date', 'id'],
            },
        ),
    ]
