# Generated by Django 6.0.3 on 2026-10-03 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copy_transaction_comments(apps, schema_editor):
    """Гүйлгээнд хадгалагдсан (хүснэгтэд харагддаггүй байсан) тэмдэглэл, өнгийг
    тухайн гүйлгээний хуваарилалт бүрийн нүд рүү хуулна."""
    BankTransaction = apps.get_model('main', 'BankTransaction')
    PaymentCellNote = apps.get_model('main', 'PaymentCellNote')
    txs = BankTransaction.objects.exclude(payment_comment='', payment_color='')
    for tx in txs:
        for alloc in tx.allocations.all():
            PaymentCellNote.objects.get_or_create(
                student_id=alloc.student_id, course_id=alloc.course_id, year=alloc.year, month=alloc.month,
                defaults={'comment': tx.payment_comment or '', 'color': tx.payment_color or ''},
            )


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0061_pending_payment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentCellNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(verbose_name='Сар')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Он')),
                ('comment', models.TextField(blank=True, verbose_name='Тэмдэглэл')),
                ('color', models.CharField(blank=True, default='', max_length=7, verbose_name='Өнгө')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course', verbose_name='Анги')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='payment_cell_notes', to='main.userprofile', verbose_name='Сурагч')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Засварласан')),
            ],
            options={
                'verbose_name': 'Төлбөрийн нүдний тэмдэглэл',
                'verbose_name_plural': 'Төлбөрийн нүдний тэмдэглэлүүд',
                'constraints': [models.UniqueConstraint(fields=('student', 'course', 'year', 'month'), name='unique_payment_cell_note')],
            },
        ),
        migrations.RunPython(copy_transaction_comments, migrations.RunPython.noop),
    ]
