# Generated by Django 6.0.3 on 2026-10-06 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0062_payment_cell_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingpayment',
            name='method',
            field=models.CharField(choices=[('BANK', 'Банкаар'), ('CASH', 'Бэлнээр'), ('POS', 'POS-оор'), ('OTHER', 'Бусад')], default='BANK', max_length=10, verbose_name='Төлсөн хэлбэр'),
        ),
    ]
