# Generated by Django 6.0.3 on 2026-10-06 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0063_pending_payment_pos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingpayment',
            name='pre_start',
            field=models.BooleanField(default=False, help_text='Кассын гүйлгээ, журналгүйгээр төлсөн гэж тооцно; хуулгатай холбогдохгүй', verbose_name='Систем эхлэхээс өмнө төлсөн'),
        ),
    ]
