# Generated by Django 6.0.3 on 2026-10-06 02:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0064_pending_payment_pre_start'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Он')),
                ('month', models.PositiveSmallIntegerField(verbose_name='Сар')),
                ('name', models.CharField(max_length=100, verbose_name='Хөнгөлөлтийн нэр')),
                ('kind', models.CharField(choices=[('PERCENT', 'Хувь (%)'), ('AMOUNT', 'Дүн (₮)')], default='PERCENT', max_length=10, verbose_name='Төрөл')),
                ('value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Хэмжээ')),
                ('comment', models.TextField(blank=True, verbose_name='Тайлбар')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course', verbose_name='Анги')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Бүртгэсэн')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='payment_discounts', to='main.userprofile', verbose_name='Сурагч')),
            ],
            options={
                'verbose_name': 'Төлбөрийн хөнгөлөлт',
                'verbose_name_plural': 'Төлбөрийн хөнгөлөлтүүд',
                'ordering': ['year', 'month'],
                'unique_together': {('student', 'course', 'year', 'month')},
            },
        ),
    ]
