# Generated by Django 6.0.3 on 2026-10-06 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0065_payment_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingentry',
            name='related_purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_entries', to='main.purchase', verbose_name='Худалдан авалт'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='kind',
            field=models.CharField(choices=[('PURCHASE', 'Худалдан авалт'), ('CONVERSION', 'Бараа хувиргалт')], default='PURCHASE', max_length=20, verbose_name='Төрөл'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='payment_method',
            field=models.CharField(blank=True, max_length=20, verbose_name='Төлбөрийн хэлбэр'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='reference_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Баримтын дугаар'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='main.purchase', verbose_name='Худалдан авалтын баримт'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='main.counterparty', verbose_name='Нийлүүлэгч'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'Бэлэн'), ('BANK', 'Данс'), ('MIXED', 'Бэлэн + Данс'), ('CREDIT', 'Зээлээр'), ('INTERNAL', 'Дотоод хэрэгцээ'), ('POS', 'POS карт'), ('CONVERSION', 'Бараа хувиргалт')], help_text='Бэлэн, данс эсвэл зээлээр', max_length=20, verbose_name='Төлбөрийн хэлбэр'),
        ),
    ]
