# Generated by Django 6.0.3 on 2026-10-08 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0067_material_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='sale_revenue_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_revenue_bank_transactions', to='main.accountingentry', verbose_name='Борлуулалтын орлогын бичилт (хосолсон)'),
        ),
    ]
